/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*! @name PORTA19 (number 7), J2[3]/D10/RGB_GREEN
  @{ */
#define BOARD_INITLEDS_LED_GREEN_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITLEDS_LED_GREEN_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITLEDS_LED_GREEN_PIN 19U    /*!<@brief PORTA pin index: 19 */
                                            /* @} */

/*! @name PORTA18 (number 6), J2[6]/D13/RGB_BLUE
  @{ */
#define BOARD_INITLEDS_LED_BLUE_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITLEDS_LED_BLUE_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITLEDS_LED_BLUE_PIN 18U    /*!<@brief PORTA pin index: 18 */
                                           /* @} */

/*! @name PORTC18 (number 47), J1[7]/U4[8]/D6
  @{ */
#define BOARD_INITLEDS_FLASH_SO_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITLEDS_FLASH_SO_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITLEDS_FLASH_SO_PIN 18U    /*!<@brief PORTC pin index: 18 */
                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDs(void);

#define SOPT5_LPUART0RXSRC_LPUART_RX 0x00u /*!<@brief LPUART0 Receive Data Source Select: LPUART_RX pin */
#define SOPT5_LPUART0TXSRC_LPUART_TX 0x00u /*!<@brief LPUART0 Transmit Data Source Select: LPUART0_TX pin */

/*! @name PORTC6 (number 42), J1[1]/D0/UART0_RX_TGTMCU
  @{ */
#define BOARD_INITLPUART_DEBUG_UART_RX_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITLPUART_DEBUG_UART_RX_PIN 6U     /*!<@brief PORTC pin index: 6 */
                                                  /* @} */

/*! @name PORTC7 (number 43), J1[2]/D1/UART0_TX_TGTMCU
  @{ */
#define BOARD_INITLPUART_DEBUG_UART_TX_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITLPUART_DEBUG_UART_TX_PIN 7U     /*!<@brief PORTC pin index: 7 */
                                                  /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLPUART(void);

/*! @name PORTC2 (number 38), J2[10]/U9[4]/D15/I2C1_SCL
  @{ */
#define BOARD_INITI2C_ACCEL_SCL_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITI2C_ACCEL_SCL_PIN 2U     /*!<@brief PORTC pin index: 2 */
                                           /* @} */

/*! @name PORTC3 (number 39), J2[9]/U9[6]/D14/I2C1_SDA
  @{ */
#define BOARD_INITI2C_ACCEL_SDA_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITI2C_ACCEL_SDA_PIN 3U     /*!<@brief PORTC pin index: 3 */
                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitI2C(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
